Crud/Pages/Galery/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Crud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.EntityFrameworkCore;

namespace Crud.Pages.Galery
{
    public class CreateModel : PageModel
    {
        private readonly Crud.Models.ApplicationDbContext _db;
        private readonly IWebHostEnvironment _iweb;
        public CreateModel(Crud.Models.ApplicationDbContext db, IWebHostEnvironment iweb)
        {
            _db = db;
            _iweb = iweb;
        }

        [BindProperty]
        public Galeria Galeria { get; set; }

        public async Task<IActionResult> OnPostAsync(IFormFile uploadfiles, Galeria img, string imgtitle)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            string imgext = Path.GetExtension(uploadfiles.FileName);
            if(imgext==".jpg" || imgext==".gif" || imgext == ".jpeg" || imgext == ".png")
            {
                
                var imgsave = Path.Combine(_iweb.WebRootPath, "Images", uploadfiles.FileName);
                var stream = new FileStream(imgsave, FileMode.Create);
                await uploadfiles.CopyToAsync(stream);
                stream.Close();
                img.Imgname = uploadfiles.FileName;
                img.Imgpath = imgsave;
                img.Imgtitle = Galeria.Imgtitle;
                await _db.Galeria.AddAsync(img);
                await _db.SaveChangesAsync();
            }
            return RedirectToPage("Index");
        }
    }
}

Crud/Pages/Galery/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Crud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.EntityFrameworkCore;

namespace Crud.Pages.Galery
{
    public class EditModel : PageModel
    {
        private readonly Crud.Models.ApplicationDbContext _db;
        private readonly IWebHostEnvironment _iweb;
        public EditModel(Crud.Models.ApplicationDbContext db, IWebHostEnvironment iweb)
        {
            _db = db;
            _iweb = iweb;
        }

        [BindProperty]
        public Galeria Galeria { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }

            Galeria = await _db.Galeria.FirstOrDefaultAsync(m => m.Id == id);

            if( Galeria == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(IFormFile uploadfiles, Galeria img, string fname, int id, string imgtitle)
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }
            _db.Attach(Galeria).State = EntityState.Modified;

            try
            {
                var Id = await _db.Galeria.FindAsync(id);
                _db.Galeria.Remove(Id);

                fname = Path.Combine(_iweb.WebRootPath, "Images", Id.Imgname);
                FileInfo fi = new FileInfo(fname);

                var imgsave = Id.Imgpath;
                String imgext;
                var FileUp = Id.Imgname;

                if (uploadfiles != null)
                {
                    if (fi.Exists)
                    {
                        System.IO.File.Delete(fname);
                        fi.Delete();
                    }
                    imgext = Path.GetExtension(uploadfiles.FileName);

                    if (imgext == ".jpg" || imgext == ".gif" || imgext == ".jpeg" || imgext == ".png")
                    {
                        imgsave = Path.Combine(_iweb.WebRootPath, "Images", uploadfiles.FileName);
                        var stream = new FileStream(imgsave, FileMode.Create);
                        await uploadfiles.CopyToAsync(stream);
                        stream.Close();
                        img.Id = id;
                        img.Imgname = uploadfiles.FileName;
                        img.Imgpath = imgsave;
                        img.Imgtitle = Galeria.Imgtitle;
                        _db.Update(img);
                        await _db.SaveChangesAsync();
                    }

                }
                else
                {
                    imgext = Path.GetExtension(Id.Imgname);

                    if (imgext == ".jpg" || imgext == ".gif")
                    {
                        img.Id = id;
                        img.Imgname = FileUp;
                        img.Imgpath = imgsave;
                        img.Imgtitle = Galeria.Imgtitle;
                       _db.Update(img);
                        await _db.SaveChangesAsync();

                    }
                }

            }

            catch(DbUpdateConcurrencyException)
            {

            }

            return RedirectToPage("Index");
        }
    }
}

Crud/Pages/Galery/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Crud.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

using Microsoft.AspNetCore.Http;
using System.IO;

namespace Crud.Pages.Galery
{
    public class IndexModel : PageModel
    {
        private readonly Crud.Models.ApplicationDbContext _db;
        private readonly IWebHostEnvironment _iweb;
        public IndexModel(Crud.Models.ApplicationDbContext db, IWebHostEnvironment iweb)
        {
            _db = db;
            _iweb = iweb;
        }
        public IEnumerable<Galeria> Galeria { get; set; }

        public async Task OnGet()
        {
            Galeria = await _db.Galeria.ToListAsync();
            
        }
        public FileResult OnGetDownloadFile(string filename)
        {
            string path = Path.Combine(_iweb.WebRootPath, "Images/")+filename;
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, "application/octet-stream", filename);
        }

        public async Task<IActionResult> OnGetDeleteAsync(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

             var Galeria = await _db.Galeria.FirstOrDefaultAsync(m => m.Id == id);

            if(Galeria == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int? id, string fname)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var Galeria = await _db.Galeria.FindAsync(id);
            _db.Galeria.Remove(Galeria);

            fname = Path.Combine(_iweb.WebRootPath, "Images", Galeria.Imgname);
            FileInfo fi = new FileInfo(fname);
            if(fi.Exists)
            {
                System.IO.File.Delete(fname);
                fi.Delete();
            }
            
            if(Galeria != null)
            {
                _db.Galeria.Remove(Galeria);
                await _db.SaveChangesAsync();
            }
            return RedirectToPage("Index");

        }

    }
}

Crud/Pages/Galery/Create.cshtml
@page
@model Crud.Pages.Galery.CreateModel
@{
    ViewData["Title"] = "Create";
}

<div class="col-xl-7 col-lg-12 d-flex bg-dark mr-auto ml-auto mt-3 formulario">
    <div class="container align-self-center p-6">
        <h1 class="font-weight-bold mb-3">Subir imagen</h1>

        <p class="text-muted mb-5">Ingresa la siguiente información para subir tu imagen</p>

        <form method="post" enctype="multipart/form-data" data-toggle="validator" role="form">

            <div class="form-group mb-3">
                <label class="font-weight-bold">Titulo de la imagen <span class="text-danger">*</span></label>
                <input asp-for="Galeria.Imgtitle" class="form-control" type="text" placeholder="Ingresa el titulo de la imagen" required />
                <span asp-validation-for="Galeria.Imgtitle" class="text-danger"></span>
            </div>

            <div class="form-group mb-5">
                <p class="text-muted">Al subir esta imagen aceptas que esta libre de derechos de autor</p>
            </div>
            <div class="form-group mb-3">
                <input type="file" name="uploadFiles" required/>
            </div>
            <input type="submit" value="Subir" class="btn btn-primary width-100" />

            <a asp-page="Index" class="btn btn-success width-100">Volver a la galeria</a>

        </form>
        <small class="d-inline-block text-muted mt-5">Todos los derechos reservados | © 2021 FreeIMG</small>
    </div>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Crud/Pages/Galery/Edit.cshtml
@page
@model Crud.Pages.Galery.EditModel
@{
}


<div class="col-xl-7 col-lg-12 d-flex bg-dark mr-auto ml-auto mt-3 formulario">
    <div class="container align-self-center p-6">
        <h1 class="font-weight-bold mb-3">Editar imagen</h1>

        <p class="text-muted mb-5">Ingresa la siguiente información para editar tu imagen</p>

        <form method="post" enctype="multipart/form-data" data-toggle="validator" role="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Galeria.Id" />

            <div class="form-group mb-3">
                <label class="font-weight-bold">Titulo de la imagen <span class="text-danger">*</span></label>
                <input asp-for="Galeria.Imgtitle" class="form-control" type="text" placeholder="Ingresa el titulo de la imagen" required />
                <span asp-validation-for="Galeria.Imgtitle" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="font-weight-bold">Archivo original</label>
                <input asp-for="Galeria.Imgname" class="form-control" readonly />
                <span asp-validation-for="Galeria.Imgname" class="text-danger"></span>
            </div>

            <div class="form-group mb-5">
                <p class="text-muted">Al subir una imagen aceptas que esta libre de derechos de autor</p>
            </div>
            <div class="form-group mb-3">
                <input type="file" name="uploadFiles" />
            </div>
            <input type="submit" value="Editar" class="btn btn-primary width-100" />

            <a asp-page="Index" class="btn btn-success width-100">Volver a la galeria</a>

        </form>
        <small class="d-inline-block text-muted mt-5">Todos los derechos reservados | © 2021 FreeIMG</small>
    </div>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Crud/Pages/Galery/Index.cshtml
@page
@model Crud.Pages.Galery.IndexModel
@{
    ViewData["Title"] = "Index";
    
}

    <div>
        <h2 class="text-center display-4 mt-5 mb-4 text-dark">Galeria</h2>
    </div>
    <div class="row">
        <div class="mb-4">
            <a asp-page="Create" class="btn btn-primary">Subir imagen</a>
        </div>
    </div>

    @if (Model.Galeria.Count() > 0)
    {
        <div class="card-columns">

            @foreach (var item in Model.Galeria)
            {
             

                <div>
                    <a href="#" data-toggle="modal" data-target="#a_@Html.DisplayFor(modelItem => item.Id)">
                        <div class="hovereffect mb-4">
                            <img src="~/Images/@item.Imgname" alt="@item.Imgname" class="card-img-top" />
                            <div class="overlay">
                                <h2>@item.Imgtitle</h2>
                            </div>
                        </div>
                    </a>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="a_@Html.DisplayFor(modelItem => item.Id)" 
                     tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

                    <button type="button" class="close mr-2" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <div class="modal-header text-white border-0">
                        <h5 class="modal-title ml-auto mr-auto" id="exampleModalLabel">@Html.DisplayFor(modelItem => item.Imgtitle)</h5>
                    </div>
                    <div class="modal-dialog modal-lg-centered modal-content mt-1" role="document">

                        <img src="~/Images/@item.Imgname" alt="@item.Imgname" class="img-fluid rounded" />
                        <div class="modal-footer border-0 position-absolute">
                            <form method="post">
                                <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('¿Esta seguro de querer eliminar esta imagen?')" class="btn btn-danger btn-sm boton">Borrar</button>
                            </form>
                            <a Asp-route-id="@item.Id" asp-page="Edit" class="btn btn-success btn-sm boton">Editar</a>
                            <a href="@Url.Page("Index","DownloadFile",new {filename = @item.Imgname})"><i class="fas fa-download color-icon fa-3x"></i></a>
                        </div>
                    </div>

                </div>
            }
        </div>
    }
    else
    {
        <p>No hay imagenes disponibles</p>
    }